apiVersion: v1
baseDomain: ${baseDomain}
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - ${az1}
      rootVolume:
        iops: 2400
        size: 300
        type: io1
      type: ${master-instance-type}
  replicas: ${master-instance-count}
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - ${az1}
      rootVolume:
        iops: 1200
        size: 300
        type: io1
      type: ${worker-instance-type}
  replicas: ${worker-instance-count}
metadata:
  name: ${clustername}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: ${machine-cidr}
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ${region}
    subnets:
    - ${subnet-1}
    - ${subnet-2}
pullSecret: '${pullSecret}'
fips: ${FIPS}
sshKey: |
  ${sshKey}
