
---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  IAM resources used by the root template and all other stack templates used to deploy the IBM Cloud Pak cluster.

Parameters:

  BootNodeRole:
    Description: >-
      BootNodeRole paramter from IAMResource for ICPD related update
    Type: String

  ExternalICPAdminLocation:
    Description: >-
      The network CIDR for IP addresses that can be used to SSH to the boot node. In single user test situations this can be a /32 CIDR.  Additional values can be added post-deployment from the AWS CloudFormation console.
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: >-
      ((\d{1,3})\.){3}\d{1,3}/\d{1,2}
    ConstraintDescription: >-
      Must be a valid IP CIDR range of the form x.x.x.x/x.

  ICPDArchiveBucketName:
    Description: >-
      The name of the S3 bucket where the ICPD install archive and Docker install binary is located.  The bucket name is needed to establish permission to access the ICP and Docker installation archives. Root template uses a mapping based on AWS region to provide the archive bucket name.
    Type: String

  ICPDScriptBucketName:
    Description: >-
      The name of the S3 bucket where the ICP boostrap script packages are located.
    Type: String

  ICPMasterSecurityGroup:
    Description: >-
      ICPMasterSecurityGroup for ICPD related update
    Type: String

  ExternalSSHSecurityGroup:
    Description: >-
      ExternalSSHSecurityGroup for ICPD related update
    Type: String

  ICPNodeRole:
    Description: >-
      ICPNodeRole paramter from IAMResource for ICPD related update
    Type: String  

Resources:
  BootPolicies: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: ICPDBootPolicy
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
        - Action:
            - s3:ListBucket
          Resource: !Sub arn:aws:s3:::${ICPDArchiveBucketName}
          Effect: Allow
        - Action:
            - s3:GetObject
          Resource: !Sub arn:aws:s3:::${ICPDArchiveBucketName}/*
          Effect: Allow
        - Action:
            - s3:ListBucket
          Resource: !Sub arn:aws:s3:::${ICPDScriptBucketName}
          Effect: Allow
        - Action:
            - s3:GetObject
          Resource: !Sub arn:aws:s3:::${ICPDScriptBucketName}/*
          Effect: Allow
        - Action:
            - ec2messages:DeleteMessage
            - ec2messages:GetEndpoint
            - ec2messages:FailMessage
            - ec2messages:AcknowledgeMessage
            - ec2messages:SendReply
          Effect: 'Allow'
          Resource:  '*'
      Roles: 
        - 
          Ref: BootNodeRole
  
  ICPPolicies: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: ICPDICPNodePolicy
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
        - Action:
            - ssm:SendCommand
            - ssm:ListCommands
            - ssm:DescribeInstanceInformation
            - ssm:GetCommandInvocation
          Effect: 'Allow'
          Resource:  '*'
      Roles: 
        - 
          Ref: ICPNodeRole 

  BootNodeProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          Ref: BootNodeRole             

  ICPNodeProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          Ref: ICPNodeRole  



  ICPDMgmtConsoleIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ICPMasterSecurityGroup
      IpProtocol: tcp
      FromPort: 31843
      ToPort: 31843
      CidrIp: !Ref ExternalICPAdminLocation

  ICPDSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ExternalSSHSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: "10.10.0.0/20"


Outputs:
  ICPMasterSecurityGroup:
    Description: >-
      ICPMasterSecurityGroup resource ID for use by parent stack template.
    Value: !Ref ICPMasterSecurityGroup

  ExternalSSHSecurityGroup:
    Description: >-
      ExternalSSHSecurityGroup resource ID for use by parent stack template.
    Value: !Ref ExternalSSHSecurityGroup

  BootNodeRole:
    Description: >-
      BootNodeRole resource ID for use by parent stack templates(s)
    Value: !Ref BootNodeRole

  ICPNodeRole:
    Description: >-
      ICPNodeRole resource ID for use by parent stack templates(s)
    Value: !Ref ICPNodeRole  
