apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: ${file-system-id}
  aws.region: ${aws-region}
  provisioner.name: openshift.org/aws-efs 
  dns.name: ${efsdnsname}